[tool.poetry]
name = "new-train-tracker"
version = "2.3.3"
description = "New Train Tracker by TransitMattters"
authors = ["TransitMatters Labs Team"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.12"
flask = "3.0.3"
aiohttp = "3.9.5"
boto3 = "1.34.87"
gunicorn = "22.0.0"
json-api-doc = "0.15.0"
pytz = "2024.1"
schedule = "1.2.1"


[tool.poetry.dev-dependencies]
pip = ">=23.3"
black = "^24.4.0"
pylint = "3.1.0"
flake8 = "7.0.0"


[tool.black]
line-length = 120
target-version = ['py312']


[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
